"""Localization module for VT Manager.
Supports English, Spanish, and Japanese.
"""

TRANSLATIONS = {
    "en": {
        "nav_model": "Models",
        "nav_chat": "AI Chat Manager",
        "nav_calendar": "Schedule",
        "nav_tasks": "Tasks",
        "nav_planning": "Planning",
        "nav_metrics": "Metrics",
        "nav_settings": "Settings",
        "nav_manual": "User Manual",
        "title_model": "Model Selection",
        "title_chat": "AI Chat Manager",
        "title_calendar": "Streaming Schedule",
        "title_tasks": "Tasks & To-Do",
        "title_planning": "Stream Planning",
        "title_metrics": "Metrics & Analytics",
        "title_settings": "Settings",
        "title_manual": "User Manual",
        "settings_hardware": "Hardware Information",
        "settings_paths": "Paths",
        "settings_memory": "Long-Term Memory Configuration (Mem0)",
        "settings_streaming": "Streaming API Configuration (OBS, Twitch, Kick)",
        "settings_twitch_bot": "Moderator & Chat Bot (Twitch)",
        "settings_voice": "Voice Interaction Settings (VAD, STT & TTS)",
        "settings_vision": "Multimodal Vision AI (LLaVA)",
        "settings_twitter": "Social Media Configuration (Twitter/X)",
        "settings_backend": "AI Backend & Model Settings",
        "settings_general": "General Application Settings",
        "lang_label": "Application Language / Idioma:",
        "restart_msg": "Language saved! Please restart the application to apply the translations to all sub-pages completely.",
        "restart_title": "Restart Recommended",
        
        # General sub-page items in Settings
        "hw_tier": "Recommended Tier",
        "paths_bin": "Bin directory",
        "paths_models": "Models directory",
        "mem_enable": "Enable Long-Term Memory (Requires GGUF model loaded)",
        "mem_backend": "Memory Backend",
        "mem_clear_btn": "Clear Memory Database",
        "stream_twitch_enable": "Enable Twitch Chat Monitoring",
        "stream_twitch_channel": "Twitch Channel:",
        "stream_kick_enable": "Enable Kick Metrics",
        "stream_kick_channel": "Kick Channel:",
        "stream_obs_enable": "Enable OBS Studio Connection",
        "stream_obs_host": "Host:Port:",
        "stream_obs_password": "Password:",
        "stream_obs_test_btn": "🔌 Test OBS Connection",
        "bot_enable": "Enable Intelligent Moderator (Twitch)",
        "bot_nick": "Bot Nickname:",
        "bot_oauth": "Bot OAuth Token:",
        "bot_note": "Note: To allow the bot to send messages, use a secondary Twitch account and generate its token at twitchapps.com/tmi/\nIt will reply to '!astra <question>' or direct mentions.",
        "voice_stt_enable": "Enable Voice Input (Microphone -> STT)",
        "voice_tts_enable": "Enable Voice Output (Astra TTS)",
        "voice_tts_engine": "TTS Engine:",
        "voice_lang": "Voice Language:",
        "voice_wake_word": "Wake Word:",
        "voice_vad_threshold": "VAD Threshold:",
        "vision_projector": "Multimodal Projector (mmproj):",
        "browse": "Browse",
        "vision_note": "Note: Requires configuring the mmproj file matching your LLaVA model.\nIt loads when starting the local llama-server.",
        "twitter_api_key": "API Key:",
        "twitter_api_secret": "API Secret:",
        "twitter_access_token": "Access Token:",
        "twitter_token_secret": "Token Secret:",
        "twitter_auto_publish": "Auto-publish 'Go Live' Tweet when streaming starts",
        "twitter_test_btn": "📢 Send Test Tweet",
        "backend_label": "AI Backend:",
        "backend_llamacpp_help": "Using Local llama.cpp. Manage GGUF models on the 'Models' page.\nAstra starts and stops llama-server.exe automatically.",
        "backend_ollama_host": "Ollama Host:",
        "backend_model_name": "Model Name:",
        "backend_ollama_setup_btn": "✨ Auto-Select & Download Model (GPU Optimized)",
        "backend_api_host": "API Host:",
        "backend_api_key": "API Key:",
        "settings_prompt": "System Prompt",
        "settings_save_btn": "💾 Save Settings"
    },
    "es": {
        "nav_model": "Modelos",
        "nav_chat": "Chat de Astra",
        "nav_calendar": "Calendario",
        "nav_tasks": "Tareas",
        "nav_planning": "Planificación",
        "nav_metrics": "Métricas",
        "nav_settings": "Ajustes",
        "nav_manual": "Manual de Usuario",
        "title_model": "Selección de Modelos",
        "title_chat": "Chat de Astra",
        "title_calendar": "Calendario de Directos",
        "title_tasks": "Tareas y Pendientes",
        "title_planning": "Planificación de Streams",
        "title_metrics": "Métricas y Analíticas",
        "title_settings": "Ajustes de la App",
        "title_manual": "Manual de Usuario",
        "settings_hardware": "Información de Hardware",
        "settings_paths": "Rutas de Archivos",
        "settings_memory": "Memoria a Largo Plazo (Mem0)",
        "settings_streaming": "Configuración de Directo (OBS, Twitch, Kick)",
        "settings_twitch_bot": "Moderador y Bot de Chat (Twitch)",
        "settings_voice": "Ajustes de Voz (VAD, STT y TTS)",
        "settings_vision": "IA de Visión Multimodal (LLaVA)",
        "settings_twitter": "Redes Sociales (Twitter/X)",
        "settings_backend": "Backend de IA y Modelos",
        "settings_general": "Configuración General de la Aplicación",
        "lang_label": "Idioma de la Aplicación / Language:",
        "restart_msg": "¡Idioma guardado! Se recomienda reiniciar la aplicación para aplicar las traducciones a todas las páginas de forma completa.",
        "restart_title": "Reinicio Recomendado",
        
        # General sub-page items in Settings
        "hw_tier": "Nivel Recomendado",
        "paths_bin": "Carpeta de ejecutables (Bin)",
        "paths_models": "Carpeta de modelos (Models)",
        "mem_enable": "Activar Memoria a Largo Plazo (Requiere cargar modelo GGUF)",
        "mem_backend": "Motor de Memoria",
        "mem_clear_btn": "Limpiar Base de Datos de Memoria",
        "stream_twitch_enable": "Activar Monitoreo del Chat de Twitch",
        "stream_twitch_channel": "Canal de Twitch:",
        "stream_kick_enable": "Activar Métricas de Kick",
        "stream_kick_channel": "Canal de Kick:",
        "stream_obs_enable": "Activar Conexión con OBS Studio",
        "stream_obs_host": "Host:Puerto:",
        "stream_obs_password": "Contraseña:",
        "stream_obs_test_btn": "🔌 Probar Conexión con OBS",
        "bot_enable": "Activar Moderador Inteligente (Twitch)",
        "bot_nick": "Nombre del Bot:",
        "bot_oauth": "Token OAuth del Bot:",
        "bot_note": "Nota: Para que el bot pueda escribir, crea o usa una cuenta secundaria y genera su token en twitchapps.com/tmi/\nResponderá a comandos '!astra <pregunta>' o menciones directas.",
        "voice_stt_enable": "Activar Entrada de Voz (Micrófono -> STT)",
        "voice_tts_enable": "Activar Salida de Voz (Astra TTS)",
        "voice_tts_engine": "Motor de TTS:",
        "voice_lang": "Idioma de Voz:",
        "voice_wake_word": "Palabra de Activación:",
        "voice_vad_threshold": "Umbral de VAD:",
        "vision_projector": "Proyector Multimodal (mmproj):",
        "browse": "Buscar",
        "vision_note": "Nota: Requiere configurar el archivo mmproj que corresponda a tu modelo LLaVA.\nSe cargará al iniciar el servidor local de Llama.",
        "twitter_api_key": "API Key:",
        "twitter_api_secret": "API Secret:",
        "twitter_access_token": "Token de Acceso:",
        "twitter_token_secret": "Token Secret:",
        "twitter_auto_publish": "Autopublicar Tweet de 'En Vivo' al detectar transmisión",
        "twitter_test_btn": "📢 Enviar Tweet de Prueba",
        "backend_label": "IA Backend:",
        "backend_llamacpp_help": "Utilizando Llama.cpp Local. Descarga y administra tus modelos GGUF en la pestaña 'Modelos'.\nAstra iniciará y detendrá llama-server.exe automáticamente.",
        "backend_ollama_host": "Ollama Host:",
        "backend_model_name": "Nombre del Modelo:",
        "backend_ollama_setup_btn": "✨ Auto-Seleccionar y Descargar Modelo (Optimizado para tu GPU)",
        "backend_api_host": "API Host:",
        "backend_api_key": "API Key:",
        "settings_prompt": "System Prompt (Instrucciones)",
        "settings_save_btn": "💾 Guardar Ajustes"
    },
    "ja": {
        "nav_model": "モデル選択",
        "nav_chat": "AI チャット管理",
        "nav_calendar": "配信スケジュール",
        "nav_tasks": "タスクリスト",
        "nav_planning": "配信計画",
        "nav_metrics": "配信統計・分析",
        "nav_settings": "設定",
        "nav_manual": "ユーザーマニュアル",
        "title_model": "モデル選択",
        "title_chat": "AI チャット管理",
        "title_calendar": "配信スケジュール",
        "title_tasks": "タスクと予定",
        "title_planning": "配信計画",
        "title_metrics": "配信統計とデータ分析",
        "title_settings": "システム設定",
        "title_manual": "ユーザーマニュアル",
        "settings_hardware": "ハードウェア情報",
        "settings_paths": "ファイルパス設定",
        "settings_memory": "長期記憶の設定 (Mem0)",
        "settings_streaming": "配信配信設定 (OBS、Twitch、Kick)",
        "settings_twitch_bot": "モデレーター＆チャットボット (Twitch)",
        "settings_voice": "音声対話設定 (VAD、STT、TTS)",
        "settings_vision": "マルチモーダルビジョン AI (LLaVA)",
        "settings_twitter": "ソーシャルメディア連携 (Twitter/X)",
        "settings_backend": "AI バックエンドとモデル設定",
        "settings_general": "アプリケーションの一般設定",
        "lang_label": "アプリ de 言語設定 / Language:",
        "restart_msg": "言語が保存されました。すべての詳細ページに翻訳を完全に適用するには、アプリケーションを再起動してください。",
        "restart_title": "再起動の推奨",
        
        # General sub-page items in Settings
        "hw_tier": "推奨ティア",
        "paths_bin": "実行フォルダ (Bin)",
        "paths_models": "モデルフォルダ (Models)",
        "mem_enable": "長期記憶を有効にする (GGUFモデルの読み込みが必要)",
        "mem_backend": "メモリエンジン",
        "mem_clear_btn": "メモリデータベースをクリア",
        "stream_twitch_enable": "Twitchチャット監視を有効化",
        "stream_twitch_channel": "Twitchチャンネル:",
        "stream_kick_enable": "Kick統計を有効化",
        "stream_kick_channel": "Kickチャンネル:",
        "stream_obs_enable": "OBS Studio接続を有効化",
        "stream_obs_host": "ホスト:ポート:",
        "stream_obs_password": "パスワード:",
        "stream_obs_test_btn": "🔌 OBSへの接続テスト",
        "bot_enable": "インテリジェントモデレーター (Twitch) を有効化",
        "bot_nick": "ボットのニックネーム:",
        "bot_oauth": "ボットのOAuthトークン:",
        "bot_note": "注意: ボットが発言できるようにするには、セカンダリアカウントを用意して twitchapps.com/tmi/ でトークンを生成してください。\nコマンド '!astra <質問>' または直接メンションに反応します。",
        "voice_stt_enable": "音声入力を有効化 (マイク -> STT)",
        "voice_tts_enable": "音声出力を有効化 (Astra TTS)",
        "voice_tts_engine": "TTSエンジン:",
        "voice_lang": "音声言語:",
        "voice_wake_word": "起動ワード:",
        "voice_vad_threshold": "VADしきい値:",
        "vision_projector": "マルチモーダルプロジェクター (mmproj):",
        "browse": "参照",
        "vision_note": "注意: LLaVAモデルに対応するmmprojファイルの設定が必要です。\nローカルのllama-server起動時に読み込まれます。",
        "twitter_api_key": "API Key:",
        "twitter_api_secret": "API Secret:",
        "twitter_access_token": "アクセス Token:",
        "twitter_token_secret": "Token Secret:",
        "twitter_auto_publish": "配信開始検出時に「配信中」ツイートを自動投稿",
        "twitter_test_btn": "📢 テストツイートを送信",
        "backend_label": "AIバックエンド:",
        "backend_llamacpp_help": "ローカルのLlama.cppを使用中。'モデル選択'タブでGGUFモデルを管理してください。\nAstraは自動的にllama-server.exeを起動・終了します。",
        "backend_ollama_host": "Ollama Host:",
        "backend_model_name": "モデル名:",
        "backend_ollama_setup_btn": "✨ モデル自動選択＆ダウンロード (GPU最適化)",
        "backend_api_host": "API Host:",
        "backend_api_key": "API Key:",
        "settings_prompt": "システムプロンプト (指示)",
        "settings_save_btn": "💾 設定を保存"
    }
}

def tr(key: str, lang: str = "en") -> str:
    """Translate the given key to the specified language."""
    if not lang:
        lang = "en"
    lang = lang.lower().strip()
    if lang not in TRANSLATIONS:
        lang = "en"
    return TRANSLATIONS[lang].get(key, TRANSLATIONS["en"].get(key, key))
